### ISSUE TITLE
asdf_validate doens't work with python 2.*

### ISSUE THREAD

**Issue by jas11** [SeismicData/asdf_validate#1]
If you run the validator using python 2.* on a valid ASDF file, there is an error:
ValueError: 'z' is a bad directive in format '%Y-%m-%dT%H:%M:%S%z'

I fixed this using the following modification to the validator.py code

                import time
                from calendar import timegm

                # Set as UTC and convert to seconds since epoch.
                starttime = starttime + 'Z'
                endtime = endtime + 'Z'
                starttime = timegm(time.strptime(
                    starttime.replace('Z','GMT'),"%Y-%m-%dT%H:%M:%S%Z"))
                endtime = timegm(time.strptime(
                    endtime.replace('Z','GMT'),"%Y-%m-%dT%H:%M:%S%Z”))

Do you want me to open a pull request? I haven't tested this on python3 yet.

**Comment by jas11** [comment]
This works on python3 for me. So I'll open a pull request if you want to accept it.

**Comment by krischer** [comment]
I should really write some tests for this. Sorry about that. 

A PR would be great :-)

**Comment by QuLogic** [comment]
I think it's already in ba732545eb61f0b0cc5cb17c549c167cd92fd86f.

**Comment by jas11** [comment]
Yeah, I got a bit impatient and committed my changes to the master without consulting you. Sorry about that.

Let me know if you want me to take back my changes.


On Nov 9, 2015, at 5:55 PM, Lion Krischer <notifications@github.com<mailto:notifications@github.com>> wrote:


I should really write some tests for this. Sorry about that.

A PR would be great :-)
