### ISSUE TITLE
Date string in waveform name does not validate if milliseconds are included

### ISSUE THREAD

**Issue by jas11** [SeismicData/asdf_validate#2]
Hello. If more precision is included in the start and end time of the waveform (for example 
'IU.GRFO.S3.MXE__1994-06-09T00:33:15.40__1994-06-09T00:34:06.11__synthetic), then the validator fails with this message:

jsonschema.exceptions.ValidationError: Additional properties are not allowed ('IU.GRFO.S3.MXZ__1994-06-09T00:33:15.40__1994-06-09T00:34:06.11__synthetic', 'IU.GRFO.S3.MXN__1994-06-09T00:33:15.40__1994-06-09T00:34:06.11__synthetic', 'IU.GRFO.S3.MXE__1994-06-09T00:33:15.40__1994-06-09T00:34:06.11__synthetic' were unexpected)

Failed validating 'additionalProperties' in schema['properties']['groups']['properties']['Waveforms']['properties']['groups']['patternProperties']['^[A-Z0-9]{1,2}\\.[A-Z0-9]{1,5}$']['properties']['datasets']:

Wenjie was pointing out that having the extra precision allows the synthetics and observed to be the same. It might be worth modifying it to specify milliseconds, since these names should be unique. Any thoughts?

**Comment by krischer** [comment]
Yes that is on purpose to not make the string too long.

The values in the data set name are also not used to calculate the actual start time - they just serve to generate a unique name. The actual start time is defined by a nano-second precision attribute on the data set. Does that answer your question/did I interpret it correctly?

**Comment by jas11** [comment]
Yeah I understand that. I think Wenjie wanted to be able to have the times to match the PDE time in CMTSOLUTION exactly. I will check with him today and see if there are any other reasons he wants milliseconds included.

**Comment by krischer** [comment]
Ah ok. If there is no strong reason to include higher precision date times in the names I would rather avoid it. Is there any use case where the names are actually not unique?

**Comment by jas11** [comment]
I can't think of any. If it's just a question of uniqueness then I think the way it's currently implemented is fine.

**Comment by krischer** [comment]
If Wenjie wants to associate some label with the waveforms he can also use the labelling functionality explained here: http://seismicdata.github.io/pyasdf/of_tags_and_labels.html

**Comment by wjlei1990** [comment]
Hi LIon,

We just made the string to what you suggests.
Originally, I though the name are associated with time, but as you mentioned, it is not.

So it is all set now.
