### ISSUE TITLE
Format version error

### ISSUE THREAD

**Issue by outdoorpet** [SeismicData/asdf_validate#3]
Hi,

I just installed the code but I am getting the following error:

"Format version 1.0.0 not known to validator. Known versions:
	0.0.2"

What does this mean? Is it the format of the ASDF file?
Thanks for developing these tools for ASDF!

**Comment by krischer** [comment]
My bad - I forgot to commit these changes. There is actually no difference between 0.0.2 and version 1.0.0 of the format. In any case if you `git pull` it should work.

Fixed in 9d4283b87f98c91f7636442b7599f85657b72958.
